import { enterprises as sourceEnterprises } from "../data";
import type { ParkBuilding, ParkViewerData } from "./types";

// Logical positions describe a demonstration layout, not surveyed GIS locations.
const enterprisePositions = [
  [23, 28],
  [53, 28],
  [83, 28],
  [23, 60],
  [53, 60],
];
const buildings: ParkBuilding[] = enterprisePositions.flatMap(([x, y], i) => [
  {
    buildingId: `factory-${i}-main`,
    name: sourceEnterprises[i].name,
    type: "factory",
    position: { x, y: y - 4 },
    width: 510,
    depth: 180,
    height: 42,
    enterpriseId: `enterprise-${i + 1}`,
    hasSolarRoof: i !== 2,
  },
  {
    buildingId: `factory-${i}-workshop`,
    name: "生产车间",
    type: "factory",
    position: { x, y: y + 3 },
    width: 510,
    depth: 160,
    height: 35,
    enterpriseId: `enterprise-${i + 1}`,
    hasSolarRoof: i !== 2,
  },
  {
    buildingId: `factory-${i}-office`,
    name: "企业办公楼",
    type: "office",
    position: { x: x - 6, y: y + 10 },
    width: 140,
    depth: 75,
    height: 65,
    enterpriseId: `enterprise-${i + 1}`,
  },
  {
    buildingId: `factory-${i}-service`,
    name: "附属用房",
    type: "service",
    position: { x: x + 7, y: y + 10 },
    width: 130,
    depth: 70,
    height: 18,
    enterpriseId: `enterprise-${i + 1}`,
  },
]);
buildings.push(
  {
    buildingId: "service-center",
    name: "园区服务中心",
    type: "office",
    position: { x: 23, y: 85 },
    width: 320,
    depth: 150,
    height: 84,
  },
  {
    buildingId: "research-center",
    name: "研发中心",
    type: "office",
    position: { x: 83, y: 85 },
    width: 240,
    depth: 130,
    height: 70,
  },
);
export const mockParkData: ParkViewerData = {
  buildings,
  enterprises: sourceEnterprises.map((e, i) => ({
    enterpriseId: `enterprise-${i + 1}`,
    name: e.name,
    position: {
      x: enterprisePositions[i][0],
      y: enterprisePositions[i][1],
      z: 65,
    },
    industry: i === 3 ? "锂电池制造" : "光伏与新能源制造",
    park: "南海子工业园区",
    isKeyEnterprise: true,
    isGreenFactory: i !== 2,
    isZeroCarbonFactory: i === 3,
    energy: e.energy,
    carbon: e.carbon,
    intensity: e.intensity,
    green: e.green,
    reduction: e.reduction,
  })),
  facilities: [
    {
      facilityId: "facility-solar",
      name: "分布式光伏",
      type: "solar",
      position: { x: 83, y: 54 },
      info: "装机 240 MW",
    },
    {
      facilityId: "facility-wind",
      name: "风力发电",
      type: "wind",
      position: { x: 80, y: 2 },
      info: "装机 548 MW",
    },
    {
      facilityId: "facility-storage",
      name: "储能电站",
      type: "storage",
      position: { x: 90, y: 68 },
      info: "容量 120 MWh",
    },
    {
      facilityId: "facility-substation",
      name: "变电站",
      type: "substation",
      position: { x: 76, y: 68 },
      info: "220 kV / 500 kV",
    },
    {
      facilityId: "facility-green-link",
      name: "绿电直连线路",
      type: "greenLink",
      position: { x: 68, y: 40 },
      info: "已建 2 条",
    },
    {
      facilityId: "facility-gas",
      name: "天然气调压站",
      type: "gas",
      position: { x: 10, y: 54 },
      info: "园区燃气管网接入",
    },
    {
      facilityId: "facility-heat",
      name: "集中供热站",
      type: "heat",
      position: { x: 42, y: 78 },
      info: "蒸汽与热水供应",
    },
  ],
  energyFlows: [
    {
      flowId: "flow-grid-1",
      sourceId: "facility-substation",
      targetId: "enterprise-1",
      energyType: "electric",
      value: 18.74,
    },
    {
      flowId: "flow-grid-2",
      sourceId: "facility-substation",
      targetId: "enterprise-3",
      energyType: "electric",
      value: 12.56,
    },
    {
      flowId: "flow-grid-3",
      sourceId: "facility-substation",
      targetId: "enterprise-5",
      energyType: "electric",
      value: 8.34,
    },
    {
      flowId: "flow-solar",
      sourceId: "facility-solar",
      targetId: "enterprise-1",
      energyType: "green",
      value: 9.28,
    },
    {
      flowId: "flow-wind",
      sourceId: "facility-wind",
      targetId: "enterprise-2",
      energyType: "green",
      value: 6.66,
    },
    {
      flowId: "flow-wind-direct",
      sourceId: "facility-wind",
      targetId: "enterprise-4",
      energyType: "green",
      value: 5.18,
    },
    {
      flowId: "flow-storage",
      sourceId: "facility-storage",
      targetId: "enterprise-4",
      energyType: "electric",
      value: 4.42,
    },
    {
      flowId: "flow-direct",
      sourceId: "facility-green-link",
      targetId: "enterprise-4",
      energyType: "green",
      value: 3.86,
    },
    {
      flowId: "flow-gas-1",
      sourceId: "facility-gas",
      targetId: "enterprise-3",
      energyType: "gas",
      value: 2.18,
    },
    {
      flowId: "flow-gas-2",
      sourceId: "facility-gas",
      targetId: "enterprise-5",
      energyType: "gas",
      value: 1.66,
    },
    {
      flowId: "flow-heat-1",
      sourceId: "facility-heat",
      targetId: "enterprise-2",
      energyType: "heat",
      value: 1.32,
    },
    {
      flowId: "flow-heat-2",
      sourceId: "facility-heat",
      targetId: "enterprise-4",
      energyType: "heat",
      value: 0.96,
    },
  ],
  carbonRegions: sourceEnterprises.map((e, i) => ({
    regionId: `carbon-region-${i}`,
    enterpriseId: `enterprise-${i + 1}`,
    position: { x: enterprisePositions[i][0], y: enterprisePositions[i][1] },
    intensity: e.intensity,
  })),
};
